name: Changelog
main: me.loidsemus.changelog.Changelog
version: @version@
author: "loidsemus"
api-version: "1.13"
description: Keep changelogs

commands:
  changelog:
    description: Main changelog command