# TODO: Edit file
name: kotlin-paper-plugin
main: me.loidsemus.plugin.Template
version: @version@
author: "loidsemus"
api-version: "1.13"
description: Kotlin paper plugin template

commands:
  main:
    description: Main command